services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rudiron
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./nextjs
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/rudiron
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=secret
      - NEXT_PUBLIC_YANDEX_CLIENT_ID=c18f082a1eaa4800a40d5224d6f7cd70
      - YANDEX_CLIENT_SECRET=1732935b0e314e3a9546abfa7650d80e
      - NEXT_PUBLIC_YANDEX_REDIRECT_URI=http://localhost:3000/auth/callback
      - NODE_ENV=development
    depends_on:
      - postgres
    volumes:
      - ./nextjs:/app
      - /app/node_modules
    command: sh -c "sleep 5 && npx prisma db push && npm run dev"

volumes:
  postgres_data: